-- return {
--    "nvim-tree/nvim-tree.lua",
--    version = "*",
--    lazy = false,
--    dependencies = {
--        "nvim-tree/nvim-web-devicons",
--    },
--    config = function()
--        require("nvim-tree").setup({
--            -- see https://github.com/nvim-tree/nvim-tree.lua for options
--            view = {
--                width = 30,
--            },
--        })
--    end,
--}
